apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ms
  labels:
    app: chat-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-ms
  template:
    metadata:
      labels:
        app: chat-ms
    spec:
      containers:
      - name: chat-ms
        image: chat-ms:latest
        env:
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
