apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-db-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete

  storageClassName: local-storage
  local:
    path: /db/psql/

  nodeAffinity:
    required:
      nodeSelectorTerms:
      # since K8 labels everything with key:val, this matches
      # all Pods running under key:val NODE
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube

# note: NODE here means one of the VMs running in the cluster
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-db-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
      - name: postgres
        image: postgres-custom:latest
        imagePullPolicy: Never
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: mango
          - name: POSTGRES_DB
            value: discordv2
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql

      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: local-db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    db: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
