apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-store
  labels: # used for grouping
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8.2.5
        ports:
        - containerPort: 6379 # the port which the app inside the container listens on

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 # open port
      targetPort: 6379 # connect to pods with label:<> on this port
